import React, { useState, useEffect } from 'react';
import { apiService } from '../services/api';
import RecommendationCard from '../components/RecommendationCard';
import { Lightbulb, Sliders, CheckCircle } from 'lucide-react';

export default function Recommendation() {
  const [recommendations, setRecommendations] = useState([]);
  const [filteredRecs, setFilteredRecs] = useState([]);
  const [confidenceFilter, setConfidenceFilter] = useState('all');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadRecs() {
      try {
        const data = await apiService.getRecommendations();
        setRecommendations(data);
        setFilteredRecs(data);
      } catch (err) {
        console.error("Error loading recommendations", err);
      } finally {
        setLoading(false);
      }
    }
    loadRecs();
  }, []);

  // Filter by confidence match score
  useEffect(() => {
    if (confidenceFilter === 'all') {
      setFilteredRecs(recommendations);
    } else {
      const minConfidence = parseInt(confidenceFilter);
      setFilteredRecs(recommendations.filter(r => r.confidence >= minConfidence));
    }
  }, [confidenceFilter, recommendations]);

  return (
    <div className="recommendation-view">
      <div className="page-header-desc">
        <p className="page-subtitle">Examine machine learning allocations. Leverage optimized timing booking windows and capacity specifications generated by our ML forecasting network.</p>
      </div>

      {/* Filter and Recommendations list */}
      <section className="advisor-section">
        <div className="listing-header">
          <h3 className="section-title">
            <Lightbulb className="sec-title-icon" /> AI Chartering Advisors
          </h3>
          <div className="list-filters">
            <Sliders className="filter-icon" />
            <select 
              value={confidenceFilter} 
              onChange={(e) => setConfidenceFilter(e.target.value)}
              className="select-input category-select"
            >
              <option value="all">All Match Scores</option>
              <option value="90">90%+ Match Score</option>
              <option value="85">85%+ Match Score</option>
              <option value="80">80%+ Match Score</option>
            </select>
          </div>
        </div>

        {loading ? (
          <div className="loading-card card">
            <div className="loader" />
            <p>Syncing booking window indices and tonnage allocations...</p>
          </div>
        ) : (
          <div className="grid-cols-3 rec-cards-grid">
            {filteredRecs.map(rec => (
              <RecommendationCard key={rec.id} recommendation={rec} />
            ))}

            {filteredRecs.length === 0 && (
              <div className="card no-recs-card">
                <CheckCircle className="check-icon" />
                <p>No active recommendations match selected threshold.</p>
              </div>
            )}
          </div>
        )}
      </section>

      <style>{`
        .recommendation-view {
          display: flex;
          flex-direction: column;
          gap: 1.5rem;
        }

        .advisor-section {
          display: flex;
          flex-direction: column;
          gap: 1rem;
        }

        /* Listings */
        .listing-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 1rem;
        }

        .section-title {
          font-family: var(--font-display);
          font-size: 1.15rem;
          color: var(--text-primary);
          display: flex;
          align-items: center;
          gap: 0.5rem;
        }

        .sec-title-icon {
          width: 1.25rem;
          height: 1.25rem;
          color: var(--color-primary);
        }

        .list-filters {
          display: flex;
          align-items: center;
          gap: 0.5rem;
        }

        .filter-icon {
          width: 0.95rem;
          height: 0.95rem;
          color: var(--text-muted);
        }

        .category-select {
          padding: 0.4rem 0.75rem;
          font-size: 0.8rem;
        }

        .loading-card {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          height: 200px;
          color: var(--text-secondary);
          gap: 1rem;
        }

        .loading-card .loader {
          width: 32px;
          height: 32px;
          border: 3px solid var(--border-color);
          border-top-color: var(--color-primary);
          border-radius: 50%;
          animation: spin 1s linear infinite;
        }

        .no-recs-card {
          grid-column: 1 / -1;
          padding: 3rem;
          text-align: center;
          color: var(--text-muted);
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          gap: 0.75rem;
        }

        .check-icon {
          width: 2rem;
          height: 2rem;
          color: var(--color-success);
        }
      `}</style>
    </div>
  );
}
